In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,5]

In [3]:
print(a)

[1, 2, 3, 4, 5]


In [4]:
print(type(a))

<class 'list'>


In [5]:
np_a=np.array(a)

In [6]:
print(np_a)

[1 2 3 4 5]


In [7]:
print(type(np_a))

<class 'numpy.ndarray'>


In [8]:
L=range(1000)
%timeit [i**2 for i in L]

104 µs ± 49.4 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
a = np.arange(1000)
%timeit a**2

3.22 µs ± 173 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [10]:
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [11]:
a.ndim

1

In [12]:
a.shape

(4,)

In [13]:
b = np.array([[0,1,2], [3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
b.ndim

2

In [15]:
b.shape

(2, 3)

In [16]:
c = np.array([[[0,1], [2,3]], [[4,5], [6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
c.ndim

3

In [18]:
c.shape

(2, 2, 2)

In [19]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [20]:
np.array(my_list)

array([1, 2, 3])

In [21]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.array(my_matrix).shape

(3, 3)

In [24]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b = np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [26]:
a = np.linspace(0,5,6)
a

array([0., 1., 2., 3., 4., 5.])

In [27]:
np.linspace(0,10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [28]:
np.zeros(3)

array([0., 0., 0.])

In [29]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [30]:
a = np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
d=np.eye(3,2)
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [33]:
a=np.diag([7,9,3,4])
a

array([[7, 0, 0, 0],
       [0, 9, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [34]:
np.diag(a)

array([7, 9, 3, 4])

In [35]:
random_array = np.random.randint(1,121,5)
print(random_array)

[ 65  15  85 118  13]


In [36]:
a = np.random.rand(4)
a

array([0.91250904, 0.40930028, 0.46609527, 0.04921065])

In [37]:
a = np.random.randn(100)
a

array([-0.99654546,  0.25193442, -0.26717379, -0.3017178 ,  2.07698381,
       -0.55640852,  0.06773926, -0.01669516, -1.22938232, -1.04138016,
       -1.89331471,  0.16804112,  0.55517622,  0.1269886 , -0.29335971,
        0.24175229,  0.44421595, -1.02878777,  0.76026283,  0.631107  ,
       -0.52637666, -0.13707041,  1.0518758 , -2.25935436, -0.292389  ,
       -0.55919334,  0.19295386,  0.84974779, -0.90761016,  0.15515223,
        0.68392682,  0.09273097, -0.04877052,  0.40854885,  0.11631974,
        0.65555775,  0.89885123,  1.39175712, -0.47635353, -1.26495697,
        0.36844717, -0.005492  , -0.73582808, -0.23886306, -0.46454206,
        0.50905461, -1.61387085,  1.28746462,  0.53519637, -0.94754029,
       -1.39918324,  0.92893665, -1.0176299 ,  0.58541227,  0.81231422,
       -0.06181983,  0.63490761,  0.23825913,  0.73384159, -0.13066626,
       -0.12050214,  1.04190215, -0.71292313,  1.06875324, -1.01611349,
       -0.25286527,  0.09832987,  0.28499838, -0.17059877, -0.24

In [38]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [39]:
arr = np.arange(25)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [40]:
a1=arr.reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print("Shape of a: {}".format(a.shape))

[[1 2 3]
 [4 5 6]]
Shape of a: (2, 3)


In [42]:
b=a.reshape(3,2)
print(b)
print("Shape of b: {}".format(b.shape))

[[1 2]
 [3 4]
 [5 6]]
Shape of b: (3, 2)


In [43]:
a=np.array([[1,2,3],[4,5,6]])
print("Shape: {}".format(a.shape))
print(a)

Shape: (2, 3)
[[1 2 3]
 [4 5 6]]


In [44]:
c=a.T
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [45]:
a=np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [46]:
c.ravel()

array([1, 4, 2, 5, 3, 6])

In [47]:
a=np.array([[5,4,6],[2,8,2]])
b=np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 2, 8]])

In [48]:
a=np.array([4,7,8])
a=np.append(a,[2,4,5])
print('Numpy array after addition:',a)

Numpy array after addition: [4 7 8 2 4 5]


In [49]:
a=np.delete(a,2)
print('Numpy array after deletion of one element:',a)

Numpy array after deletion of one element: [4 7 2 4 5]


In [50]:
a=np.arange(3,10)
print(a)
print(a[5])

[3 4 5 6 7 8 9]
8


In [51]:
a=np.diag([1,2,3])
print(a)
print(a[2,1])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
0


In [52]:
a[2,1]=5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [53]:
a=np.arange(4,18)
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [54]:
a[1:8:2]

array([ 5,  7,  9, 11])

In [55]:
a=np.arange(10)
a[5:]

array([5, 6, 7, 8, 9])

In [56]:
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [57]:
b=np.arange(5)
b

array([0, 1, 2, 3, 4])

In [58]:
b[::-1]

array([4, 3, 2, 1, 0])

In [59]:
a[5:]=b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [60]:
a=np.random.randint(0, 20, 5)
a

array([ 2,  2,  3,  1, 18])

In [61]:
a[a % 2 == 0]

array([ 2,  2, 18])

In [62]:
a[a%2==0]=-1
a

array([-1, -1,  3,  1, -1])

In [63]:
a=np.arange(0, 101, 10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [64]:
a[[9, 7]]= -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200,  100])

In [65]:
a=np.array([1,2,3,4])
print(a)
print(a+1)

[1 2 3 4]
[2 3 4 5]


In [66]:
a**2

array([ 1,  4,  9, 16])

In [67]:
b=np.ones(4)+1
b

array([2., 2., 2., 2.])

In [68]:
a-b

array([-1.,  0.,  1.,  2.])

In [69]:
a*b

array([2., 4., 6., 8.])

In [70]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[4,4],[4,4],[4,4]])
print('Sum of a and b :\n',a+b)

Sum of a and b :
 [[ 5  6]
 [ 7  8]
 [ 9 10]]


In [71]:
print('Product of a and b:\n', a*b)

Product of a and b:
 [[ 4  8]
 [12 16]
 [20 24]]


In [72]:
c=np.diag([1,2,3,4])
print(c * c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [73]:
a = np.array([[1,2,1],[3,4,3],[5,6,5]])
b = np.array([[4,4,1],[4,4,2],[4,4,3]])
print('Matrix multiplication:\n',np.matmul(a,b))

Matrix multiplication:
 [[16 16  8]
 [40 40 20]
 [64 64 32]]


In [74]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [75]:
a > b

array([False, False,  True, False])

In [76]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])

In [91]:
np.array_equal(a, b)

False

In [92]:
np.array_equal(a,c)

False

In [78]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
np.logical_or(a, b)

array([ True,  True,  True, False])

In [79]:
np.logical_and(a, b)

array([ True, False, False, False])

In [80]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [81]:
np.log(a)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17980\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [82]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [83]:
a = np.arange(4)
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [ ]:
x = np.array([1, 2, 3,4])
np.sum(x)

In [ ]:
x = np.array([[1,1,],[2,2]])
x

In [ ]:
x.sum(axis=0)

In [84]:
x.sum(axis=1)

NameError: name 'x' is not defined

In [85]:
x = np.array([1, 3, 2])
x.min()

1

In [86]:
x.max()

3

In [87]:
x.argmin()

0

In [88]:
x.argmax()

1

In [90]:
normal_array = np.arange(0,10,1)
print('Array is ',format(normal_array))
print('min element is ',np.min(normal_array))
print('max element is ',np.max(normal_array))
print('Sum of elements on array is ',np.sum(normal_array))
print('mean of elements in array is ',np.mean(normal_array))
print('median of elements in array is ',np.median(normal_array))
print('standard deviation of elements in array is ',np.std(normal_array))

Array is  [0 1 2 3 4 5 6 7 8 9]
min element is  0
max element is  9
Sum of elements on array is  45
mean of elements in array is  4.5
median of elements in array is  4.5
standard deviation of elements in array is  2.8722813232690143
